package com.petnexusai.service.ai;

/**
 * Defines the contract for any generative AI service.
 * This allows for a flexible architecture where different AI providers
 * (like OpenAI, Gemini, etc.) can be used interchangeably.
 */
public interface GenerativeAiService {

    /**
     * Generates a response from the AI model based on a given prompt.
     *
     * @param prompt The input text to send to the AI model.
     * @return The text response generated by the model.
     */
    String generateResponse(String prompt);
}